<?php

    namespace App\Traits;
    use Illuminate\Http\Response;
    
    Trait ApiResponser{

    // this code is changes since the message to return is already formatted by API responser of each site       
    public function successResponse($data, $code = Response::HTTP_OK)
    {	       
        return response($data, $code)->header('Content-Type', 'application/json');
    }

    //builds valid response
    public function validResponse($data, $code = Response::HTTP_OK)
    {
        return response()->json(['data' => $data], $code);
    }

    // error response generated by api gateway itself 	
	public function errorResponse($message, $code)
	{
	    return response()->json(['error' => $message, 'code' => $code], $code);
    }
    
    //Add errorMessage will return message generate by our API’s 
	public function errorMessage($message, $code)
	{
	    return response($message, $code)->header('Content-Type', 'application/json');
    }
    
    }
?>